### ISSUE TITLE
感觉发包间隔还能压缩的样子

### ISSUE THREAD

**Issue by Tinhone** [dd-center/DDatBrowser#3]
想稍微改一下脚本（
改完之后如果作者大大能同意合并到这个项目就更好了_(:з)∠)_

**Comment by simon300000** [comment]
👀你是说把interval变低吗 再低似乎会被风控 反而影响正常使用bilibili

**Comment by Tinhone** [comment]
我测了一下，interval已经成功压到650了

**Comment by simon300000** [comment]
那么低 似乎有可能影响正常使用bilibili哎

**Comment by Tinhone** [comment]
加到700~800？
700测了一段时间了，看上去对正常使用哔哩哔哩没什么影响🤔

**Comment by simon300000** [comment]
一开始我写的差不多就是700，但是长时间使用有可能造成影响，所以就改高了点，毕竟用户想要改还是可以自己改设置的

**Comment by Tinhone** [comment]
冷却机制应该会解决可能出现的问题，我这些天使用下来都是正常的
有不少用户不清楚怎么修改脚本，所以个人认为默认值尽量低一些更好

**Comment by Tinhone** [comment]
拉取请求那里已经改成800了，您再看一下？

**Comment by simon300000** [comment]
好呐 我晓得咯

**Comment by UnderTides** [comment]
你这边说的600、700指的是什么？毫秒还是秒？
我这边是10-60秒进行一次关注的操作，而且还是利用selenium控制真实浏览器来操作的，还是被风控了，有什么办法吗555

**Comment by UnderTides** [comment]
想向你请教一些问题
1、你这边说的600、700指的是什么？毫秒还是秒？
2、我这边是10-60秒进行一次关注的操作，而且还是利用selenium控制真实浏览器来操作的，还是被风控了，有什么办法吗。。。

**Comment by simon300000** [comment]
> 想向你请教一些问题
> 1、你这边说的600、700指的是什么？毫秒还是秒？
> 2、我这边是10-60秒进行一次关注的操作，而且还是利用selenium控制真实浏览器来操作的，还是被风控了，有什么办法吗。。。

毫秒，不太清楚关注，我这里没有尝试过（
